### ISSUE TITLE
Error while run.bat 

### ISSUE THREAD

**Issue by AImmd** [sdfxai/sdfx#1]
System: Windows
GPU: Nvidia RTX3090

I installed with with run.bat, everything works fine, while i run the run.bat, this error in the image appears.

![Screenshot 2024-04-09 082142](https://github.com/sdfxai/sdfx/assets/135707290/f514aa88-d941-4e82-8d3d-c40854dc7605)

Also this windows opend after the Error.

![grafik](https://github.com/sdfxai/sdfx/assets/135707290/0ef1852a-3435-4832-9da8-937b99934e5d)

**Comment by AImmd** [comment]
Ok i tried to reinstall it and found that this could cause the issue:

![grafik](https://github.com/sdfxai/sdfx/assets/135707290/8bd3ab22-65b5-4cee-b88e-fa935e61b849)

I will try to fix it and let you know

**Comment by dmx974** [comment]
Great, thank you. Also do not forget to go to /src and rename .env.example to .env
