### ISSUE TITLE
crypto.randomUUID() will fail, if SDFX launched not on localhost.

### ISSUE THREAD

**Issue by morgan55555** [sdfxai/sdfx#11]
PromptTimeline.vue is using crypto.randomUUID() for uuid generation.
Using crypto.randomUUID() work on https-sites, but cannot be used on http-sites (except localhost), because crypto is undefined there.
It's better to use uuidv4() from 'uuid' package (which already used by this project).

**Comment by dmx974** [comment]
Fixed
