### ISSUE TITLE
[Possible Future Request] Allow local instance of ComfyUI to be optional to connect remote IP of ComfyUI

### ISSUE THREAD

**Issue by claychinasky** [sdfxai/sdfx#2]
Hi,

as title says, not forcing local instance of ComfyUI to be run and connect already running remote IP of ComfyUI:
in my setup, I access remote ComfyUI as its in my local network via custom VPN and rerouting. (its possible that it doesn't have to be local network but public network as well.)
I haven't looked at the code where it can be configured that way, but I didn't see any option to be a settings to configure. 
or is there a way to accomplish this?

**Comment by kevin96666** [comment]
You need to run sdfx specifying the IP of your ComfyUI server
You Need to rename .env.example to .env (https://github.com/sdfxai/sdfx/blob/main/src/.env.example) and fill il with the IP

Also, don't forget to run your ComfyUI with cors enabled (python main.py --cors)

**Comment by claychinasky** [comment]
> You need to run sdfx specifying the IP of your ComfyUI server You Need to rename .env.example to .env (https://github.com/sdfxai/sdfx/blob/main/src/.env.example) and fill il with the IP
> 
> Also, don't forget to run your ComfyUI with cors enabled (python main.py --cors)

I tried to change the IP addresses but yet sdfx still spawns its own local ComfyUI and connects it as a backend.
On remote ComfyUI, many custom nodes and sdfx bridge installed. It is accessible via http and ws, and I'm only modifying local sdfx settings.

**Comment by dmx974** [comment]
Added a network tab in settings. Should fix this issue.

**Comment by claychinasky** [comment]
Thanks for the quick work, I'm was able to connect remote ComfyUI.
