### ISSUE TITLE
Any docker support?

### ISSUE THREAD

**Issue by Reekomer** [sdfxai/sdfx#21]
Hi there,

I have been trying to run the project in a docker container. I managed to have this screen : 
![image](https://github.com/sdfxai/sdfx/assets/17747150/cf2ece28-e54d-4ee2-af25-67b88bbf4dfe)

However, the following errors are preventing me from building anything:
`[17682:0502/172139.743047:ERROR:gl_surface_egl.cc(321)] No suitable EGL configs found.
[17682:0502/172139.743307:ERROR:gl_context_egl.cc(140)] eglGetConfigAttrib failed with error EGL_BAD_CONFIG
[17682:0502/172139.744703:ERROR:gl_surface_egl.cc(321)] No suitable EGL configs found.
[17682:0502/172139.744816:ERROR:gl_surface_egl.cc(1110)] eglCreatePbufferSurface failed with error EGL_BAD_CONFIG
[17682:0502/172139.744900:ERROR:gpu_info_collector.cc(80)] gl::GLContext::CreateOffscreenGLSurface failed
[17682:0502/172139.745013:ERROR:gpu_info_collector.cc(401)] Could not create surface for info collection.
[17682:0502/172139.745098:ERROR:gpu_init.cc(88)] CollectGraphicsInfo failed.
[17682:0502/172139.747431:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[17781:0502/172139.821088:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.
[17693:0502/172139.826036:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.`

Any idea how I could solve it?

**Comment by morgan55555** [comment]
Simple dockerfile and launch scripts:

```
# From official node docker (alpine)
FROM node:18.9.1-alpine3.16

# Install base packages
RUN --mount=type=cache,target=/var/cache/apk \
    apk update \
    && apk add git

# Download SDFX AI
WORKDIR /home/runner
RUN git clone --depth=1 --no-tags --recurse-submodules --shallow-submodules \
    https://github.com/sdfxai/sdfx.git

# Set backend address
ARG BACKEND_HTTP_ENDPOINT="http://localhost:8188"
ARG BACKEND_WS_ENDPOINT="http://localhost:8188"
ENV VITE_HTTP_ENDPOINT $BACKEND_HTTP_ENDPOINT
ENV VITE_WS_ENDPOINT $BACKEND_WS_ENDPOINT

# Install SDFX AI deps
WORKDIR /home/runner/sdfx/src
RUN --mount=type=cache,target=/.npm \
    npm install \
    && npm install -g serve

# Set to prod instead of dev
ENV NODE_ENV "production"

# Build SDFX AI
RUN --mount=type=cache,target=/.npm \
    npm run build:front:web \
    && rm -fr node_modules

# Copy launch script
COPY launch.sh /home/runner/

# Launch
EXPOSE 8000
WORKDIR /home/runner
ENV CLI_ARGS=""
ENTRYPOINT ["sh", "/home/runner/launch.sh"]
```

```
#!/bin/sh

set -e

cd /home/runner/sdfx/src
npx serve -s dist -l 8000 ${CLI_ARGS}
```

**Comment by Reekomer** [comment]
Thank you very much @morgan55555 ! I will try it later on and give you my feedback (potentially close the Issue)

**Comment by Reekomer** [comment]
The UI is running perfectly! My issue is that the WebSocket has an invalid URL provided. I am looking into it: 
<img width="1440" alt="image" src="https://github.com/sdfxai/sdfx/assets/17747150/d779227d-c3c4-4f16-b3bd-c5319e6388f1">

**Comment by Reekomer** [comment]
The reason why it isn't running is because ComfyUI needs to be set up and it isn't done in the Dockerfile. I will add it and share it when done.

**Comment by morgan55555** [comment]
Sorry, my bad, use ws://localhost:8188 instead of http.

And yes, you need to setup ComfyUI first, with sdfx.config.json and SDFXBridgeForComfyUI, also I recommend to include ComfyUI-Manager and ComfyUI-Crystools for node installing and server monitoring.
Also it's better to make docker volume for entire ComfyUI setup (for updating ComfyUI throug manager).

I currently use separate dockerfile's (for backend and frontend) with docker compose

**Comment by Reekomer** [comment]
Thank you for the guidance. I will try it and comment later :)

**Comment by Reekomer** [comment]
I am back to my original errors. I will pause my investigation and use Gradio as Frontend.
