### ISSUE TITLE
The SDFX app will only start once.

### ISSUE THREAD

**Issue by DaemonAlchemist** [sdfxai/sdfx#25]
I installed the SDFX on Windows 11 with an already installed ComfyUI instance according to the instructions.  The app started once, and I was able to see and use a ComfyUI workflow.  However, the app eventually stopped responding and then refused to open again.  I needed to delete the roaming data in order for the app to start up again.  However, it will now not allow editing any workflows.

Edit: I have the same issue if I install ComfyUI via the SDFX setup script.

Edit:  Running the webapp version makes it seem like the issue is in the AppList.vue component.  n.meta is undefined on lines 175 and 181.  Checking for null there seems to allow the app to load.

**Comment by S0LTIS** [comment]
Because it's pure garbage.

**Comment by DaemonAlchemist** [comment]
All programs have bugs.  There's no need for comments like that.

**Comment by dmx974** [comment]
Fixed
