### ISSUE TITLE
Feature request - MultiGPU support

### ISSUE THREAD

**Issue by upq** [sdfxai/sdfx#26]
Hello, thank you so much for your spectacular work, havent tested it yet, but right out of the bat I have a feature request i didnt read in the readme, support for multiple GPU setups, utilize VRAM and compute. 

Every time I hear about a a new diffusion UI or APP I always wish and look for that feature.

Thank you again and have a good one.

**Comment by dmx974** [comment]
Thank you, I will see with the folks @ Comfy to see how / if possible
