### ISSUE TITLE
Just white window?

### ISSUE THREAD

**Issue by mnn** [sdfxai/sdfx#5]
I have local comfyUI, installed SDFXBridgeForComfyUI and followed the steps in readme:

```
  cd src 
  npm install
  npm run start
```

It opens a window, few seconds a tile with black text SDFX on white background is spinning on gray background, then all I see is empty white space with electron menu at top.

I tried `npm run build:electron` and ran the sdfx binary from `/src/dist_electron/linux-unpacked`, but the result is exactly same. At least got some new error (this didn't show in `npm run start`):

```sh
❯ ./sdfx --trace-warnings
(node:1020331) electron: Failed to load URL: file:///mnt/dev/ai/sdfx/src/dist_electron/linux-unpacked/resources/app.asar/dist_electron/index.html with error: ERR_FILE_NOT_FOUND
```
<img width="966" alt="2024-04-12_13-28" src="https://github.com/sdfxai/sdfx/assets/1975567/92cff6a8-5835-465b-ab79-158a68660947">

I even tried copying the example config file, but it didn't change anything.

Manjaro, node 18.9.1, 8b4196936c7f02c781d4819c5da6ef574ec90b14

**Comment by dmx974** [comment]
We can reproduce the same thing on Windows 10. Still on it.

**Comment by dmx974** [comment]
Fixed
