### ISSUE TITLE
Problem loading checkpoints from App ui

### ISSUE THREAD

**Issue by claychinasky** [sdfxai/sdfx#7]
I have ComfyUI with set symbolic linked checkpoints directory, it works in native ComfyUI.
It works in sdfx graph UI if I select the checkpoint from sdfx graph UI.
But after changing a new checkpoint in App ui, it gives an error, (and which I can't close the error popup)
![image](https://github.com/sdfxai/sdfx/assets/14942524/7ac28d5a-de8a-43ae-804a-5275a2369d9e)
and in comfyUI terminal:
```invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}```
I suspect that is something to do with symbolic links maybe, because most of the python AI projects I know of, don't seem to work symbolic links by default.

**Comment by claychinasky** [comment]
after trying few things still not sure its related to symbolic links. also getting this error frequently:
![image](https://github.com/sdfxai/sdfx/assets/14942524/9b73797b-f6a1-461c-a0dc-cf8be2c72624)

**Comment by dmx974** [comment]
> after trying few things still not sure its related to symbolic links. also getting this error frequently: 

that one is related to a bug in group node not correctly instantiated, I'm fixing it

**Comment by dmx974** [comment]
Fixed
